Fix Lucene SDK issues
upmem/pim-lucene pull request #5
Opened 2024-09-23 09:35 UTC by Noah-ney

update pim-lucene depending on the new version of SDK

2024-10-08 15:14 UTC, yberthier requested changes
In our use cases we have to run Lucene over different number of DPUs.

It could be better to set NR_DPUS as environnement variable instead of touching the source code.

2024-10-08 15:14 UTC, yberthier commented on lucene/pim-benchmarks/exact_phrase/Makefile
> +NB_DPUS=1024
Let 2048

2024-10-08 15:14 UTC, yberthier commented on lucene/pim-benchmarks/exact_phrase/Makefile
Let as before

2024-10-14 15:12 UTC, SylvanBrocard requested changes
lgtm
Just add a mention of that environment variable in the README.

2024-10-15 09:30 UTC, SylvanBrocard approved these changes

2024-10-15 12:11 UTC, merged